<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Nexus.Sam</RootNamespace>
    <AssemblyName>Nexus.Sam</AssemblyName>
    <Description>Nexus Sam — China 2nd-gen ID card SAM reader (Phase D-8)</Description>
    <PackageTags>industrial-communication sam idcard identity</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>true</IncludeSource>
    <DebugType>portable</DebugType>
    <NoWarn>CS0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
  </ItemGroup>
</Project>
