<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Nexus</RootNamespace>
    <AssemblyName>Nexus.Core</AssemblyName>
    <Description>Nexus Core — Industrial communication abstractions</Description>
    <PackageTags>industrial-communication PLC protocol</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>true</IncludeSource>
    <DebugType>portable</DebugType>
  </PropertyGroup>

</Project>
