<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Nexus.Mitsubishi\Nexus.Mitsubishi.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Core\Nexus.Core.csproj" />
  </ItemGroup>
</Project>
