<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Nexus.Dnp3</RootNamespace>
    <AssemblyName>Nexus.Dnp3</AssemblyName>
    <Description>Nexus DNP3 — Distributed Network Protocol v3 implementation</Description>
    <PackageTags>industrial-communication SCADA protocol DNP3 power-utility</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>true</IncludeSource>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj"/>
  </ItemGroup>

</Project>
