const { contextBridge, ipcRenderer } = require("electron");

const allowedCommands = new Set([
  "list_serial_ports",
  "list_network_interfaces",
  "list_usb_devices",
  "set_interface_ip",
  "get_serial_status",
  "open_serial_port",
  "close_serial_port",
  "get_backend_status",
  "validate_serial_config_core",
  "read_holding_registers_once",
  "read_input_registers_once",
  "read_coils_once",
  "read_discrete_inputs_once",
  "write_single_coil_once",
  "write_single_register_once",
  "write_multiple_coils_once",
  "write_multiple_registers_once",
  "open_tcp_connection",
  "open_udp_connection",
  "close_connection",
  "tcp_read_coils",
  "tcp_read_discrete_inputs",
  "tcp_read_holding_registers",
  "tcp_read_input_registers",
  "tcp_write_single_coil",
  "tcp_write_single_register",
  "tcp_write_multiple_coils",
  "tcp_write_multiple_registers",
  "udp_read_coils",
  "udp_read_discrete_inputs",
  "udp_read_holding_registers",
  "udp_read_input_registers",
  "udp_write_single_coil",
  "udp_write_single_register",
  "udp_write_multiple_coils",
  "udp_write_multiple_registers",
  "decode_values",
  "scan_station_ids",
  "scan_serial_stations",
  // 三菱 MC 协议
  "mc_parse_address",
  "mc_build_read",
  "mc_build_write",
  "mc_parse_response",
  "open_mc_tcp_connection",
  "mc_tcp_read",
  "mc_tcp_write",
  "start_mc_tcp_slave",
  "stop_mc_slave",
  "mc_slave_set",
  // 三菱 MC 进阶(M2)
  "mc_tcp_read_random",
  "mc_tcp_write_random",
  "mc_tcp_read_blocks",
  "mc_remote_run",
  "mc_remote_stop",
  "mc_remote_reset",
  "mc_remote_pause",
  "mc_read_clock",
  "mc_echo_test",
  "mc_read_cpu_type",
  "mc_read_cpu_status",
  "mc_build_ascii_read",
  "open_mc_ascii_connection",
  "mc_ascii_read",
  "mc_ascii_write",
  // 三菱 MC 串口 C24(3C/4C 离线组帧)
  "mc_serial_build_3c",
  "mc_serial_parse_3c",
  // 三菱 A-1E / SLMP-1E 帧
  "mc_1e_build_read",
  "mc_1e_build_write",
  "mc_1e_parse",
  "open_mc_udp_connection",
  "mc_udp_read",
  "mc_udp_write",
  "mc_c24_read",
  "mc_c24_parse_read",
  "mc_c24_serial_read",
  "open_mc_1e_tcp",
  "mc_1e_read",
  "mc_1e_write",
  // 西门子 S7comm
  "brand_parse_address",
  "fins_parse_address",
  "open_fins_tcp",
  "open_fins_udp",
  "fins_read",
  "fins_write",
  "start_fins_slave",
  "stop_fins_slave",
  "fins_slave_set",
  "fins_slave_get",
  "s7_parse_address",
  "open_s7_connection",
  "s7_read",
  "s7_write",
  "start_s7_slave",
  "stop_s7_slave",
  "s7_slave_set",
  "s7_slave_get",
  "s7_cpu_control",
  "s7_read_status",
  "s7_password",
  "open_fw_tcp",
  "fw_read",
  "fw_write",
  "start_fw_slave",
  "stop_fw_slave",
  "open_ppi_tcp",
  "ppi_read",
  "ppi_write",
  "start_ppi_slave",
  "stop_ppi_slave",
  "uss_build_request",
  "uss_parse_response",
  "rk512_build_read",
  "rk512_build_write",
  "rk512_parse_response",
  "export_diagnostics",
  "s7web_connect",
  "s7web_disconnect",
  "s7web_is_connected",
  "s7web_read",
  "s7web_write",
  "s7web_ping",
  // 三菱 FX 串口协议(Computer Link / 编程口)
  "fx_links_build",
  "fx_links_parse",
  "fx_links_read",
  "fx_links_write_bits",
  "fx_links_write_words",
  "fx_prog_build_read",
  "fx_prog_build_write",
  "fx_prog_parse",
  "fx_serial_transact",
  "tcp_mask_write_register",
  "tcp_read_write_multiple",
  "tcp_read_device_id",
  "tcp_diagnostics",
  "tcp_read_exception_status",
  "tcp_get_comm_event_counter",
  "tcp_get_comm_event_log",
  "tcp_report_slave_id",
  "start_poll",
  "stop_poll",
  "get_poll_status",
  "scan_baud_rate",
  "execute_commands",
  "start_tcp_slave",
  "stop_slave",
  "slave_set_value",
  "slave_set_coil",
  "slave_clear",
  "slave_get_memory",
  // 串口调试
  "debug_send",
  "debug_set_receive",
  "debug_set_send",
  "debug_set_crc",
  "debug_clear_log",
  "debug_get_log",
  "debug_attach",
  "debug_detach",
  "compute_crc16",
  "compute_lrc",
  "parse_frame_online",
  "parse_frame_offline",
  "start_poll_stream",
  "stop_poll_stream",
  "parse_frame_offline",
  "export_csv",
  "export_json",
  "export_trace",
  "start_serial_slave",
  "stop_serial_slave",
  "serial_slave_set_value",
  "serial_slave_get_memory",
  "start_realtime_push",
  "stop_realtime_push",
  "get_realtime_status",
]);

contextBridge.exposeInMainWorld("nexusDesktop", {
  platform: process.platform,
  invoke(command, args = {}) {
    if (!allowedCommands.has(command)) {
      return Promise.reject(new Error(`不允许调用桌面命令：${command}`));
    }
    return ipcRenderer.invoke(`nexus:${command}`, args);
  },
  onPollData(callback) {
    const handler = (_event, data) => callback(data);
    ipcRenderer.on("nexus:poll_data", handler);
    return () => ipcRenderer.removeListener("nexus:poll_data", handler);
  },
  onPollError(callback) {
    const handler = (_event, error) => callback(error);
    ipcRenderer.on("nexus:poll_error", handler);
    return () => ipcRenderer.removeListener("nexus:poll_error", handler);
  },
  onDebugFrame(callback) {
    const handler = (_event, record) => callback(record);
    ipcRenderer.on("nexus:debug_frame", handler);
    return () => ipcRenderer.removeListener("nexus:debug_frame", handler);
  },
});
