<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Nexus.Schneider.Modicon\Nexus.Schneider.Modicon.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Inovance.H5u\Nexus.Inovance.H5u.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Mitsubishi.Fx5u\Nexus.Mitsubishi.Fx5u.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Siemens.S7Plus\Nexus.Siemens.S7Plus.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Omron.NxNj\Nexus.Omron.NxNj.csproj" />
    <ProjectReference Include="..\..\src\Nexus.EtherNetIp\Nexus.EtherNetIp.csproj" />
    <ProjectReference Include="..\..\src\Nexus.CcLinkIe\Nexus.CcLinkIe.csproj" />
    <ProjectReference Include="..\..\src\Nexus.Hart\Nexus.Hart.csproj" />
  </ItemGroup>
</Project>
