<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Nexus.Fuji</RootNamespace>
    <AssemblyName>Nexus.Fuji</AssemblyName>
    <Description>Nexus Fuji protocol implementation</Description>
    <PackageTags>industrial-communication PLC protocol Fuji</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>true</IncludeSource>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj"/>
  </ItemGroup>
</Project>
